import "dotenv/config";
import mongoose from "mongoose";
import { Recipe } from "../src/models/Recipe";

/**
 * Adds 24 more recipes (bringing the total to 36), spread across a wide
 * range of cuisines/diet types so cuisine+diet filters have real
 * coverage. Owned by the seeded demo user (scripts/seedDemoUser.ts).
 * Run: `npx ts-node scripts/seedRecipesBatch2.ts`
 */

const photo = (id: string) => `https://images.unsplash.com/photo-${id}?w=1600&h=1000&fit=crop&q=80`;

const RECIPES = [
  {
    title: "Osso Buco Milanese",
    shortDescription: "Braised veal shanks in a rich white wine gremolata sauce.",
    fullDescription:
      "Veal shanks slow-braised until fall-off-the-bone tender in a white wine and tomato broth, finished with a bright lemon-garlic gremolata. A classic Milanese Sunday dinner.",
    ingredients: [
      "4 veal shanks, tied",
      "1/2 cup flour, for dredging",
      "1 onion, diced",
      "2 carrots, diced",
      "2 celery stalks, diced",
      "1 cup dry white wine",
      "2 cups beef stock",
      "1 can crushed tomatoes",
      "Zest of 1 lemon",
      "2 cloves garlic, minced",
      "Fresh parsley, chopped",
    ],
    instructions: [
      "Dredge veal shanks in flour and sear in a heavy pot until browned on all sides.",
      "Remove shanks, sauté onion, carrot, and celery until softened.",
      "Deglaze with white wine, then add stock and crushed tomatoes.",
      "Return shanks to the pot, cover, and braise on low heat for 2-2.5 hours until tender.",
      "Mix lemon zest, garlic, and parsley into a gremolata.",
      "Sprinkle gremolata over shanks just before serving with risotto or crusty bread.",
    ],
    cuisineType: "Italian",
    dietType: "non-veg",
    prepTimeMinutes: 150,
    difficulty: "Hard",
    imageUrl: photo("1633436375153-d7045cb93e38"),
    ratingAverage: 4.7,
    ratingCount: 92,
  },
  {
    title: "Vegan Pesto Pasta",
    shortDescription: "Fusilli tossed in a dairy-free basil and walnut pesto.",
    fullDescription:
      "A quick weeknight pasta with a bright, herby pesto made from basil, walnuts, and nutritional yeast instead of parmesan - fully plant-based but just as rich.",
    ingredients: [
      "12 oz fusilli pasta",
      "2 cups fresh basil leaves",
      "1/2 cup walnuts",
      "3 tbsp nutritional yeast",
      "2 cloves garlic",
      "1/2 cup olive oil",
      "1 tbsp lemon juice",
      "Salt to taste",
      "Cherry tomatoes, halved, for garnish",
    ],
    instructions: [
      "Cook fusilli in salted water until al dente, reserving 1/2 cup pasta water.",
      "Blend basil, walnuts, nutritional yeast, garlic, and olive oil into a smooth pesto.",
      "Stir in lemon juice and season with salt.",
      "Toss hot pasta with pesto, loosening with reserved pasta water as needed.",
      "Top with halved cherry tomatoes and serve warm.",
    ],
    cuisineType: "Italian",
    dietType: "vegan",
    prepTimeMinutes: 20,
    difficulty: "Easy",
    imageUrl: photo("1576402187878-974f70c890a5"),
    ratingAverage: 4.4,
    ratingCount: 61,
  },
  {
    title: "Vegetable Tempura Udon",
    shortDescription: "Warm udon noodle soup topped with crispy vegetable tempura.",
    fullDescription:
      "A comforting bowl of udon noodles in a light soy-dashi broth, topped with crunchy tempura-battered vegetables. Restaurant-style, made simple at home.",
    ingredients: [
      "2 portions fresh udon noodles",
      "4 cups vegetable dashi broth",
      "3 tbsp soy sauce",
      "1 tbsp mirin",
      "1 sweet potato, sliced",
      "1 small eggplant, sliced",
      "4 shiitake mushrooms",
      "1 cup tempura batter mix, prepared",
      "Sliced scallions, for garnish",
    ],
    instructions: [
      "Whisk soy sauce and mirin into the warm dashi broth.",
      "Cook udon noodles according to package instructions, drain.",
      "Dip sweet potato, eggplant, and shiitake in tempura batter and fry until golden and crisp.",
      "Divide noodles into bowls and ladle hot broth over them.",
      "Top with tempura vegetables and scallions, serve immediately while crisp.",
    ],
    cuisineType: "Japanese",
    dietType: "vegetarian",
    prepTimeMinutes: 35,
    difficulty: "Medium",
    imageUrl: photo("1552332386-f8dd00dc2f85"),
    ratingAverage: 4.5,
    ratingCount: 74,
  },
  {
    title: "Vegan Sushi Rolls",
    shortDescription: "Avocado, cucumber, and pickled radish maki rolls.",
    fullDescription:
      "Classic hosomaki rolled with seasoned sushi rice and nori, filled with creamy avocado, crisp cucumber, and tangy pickled radish - no fish required.",
    ingredients: [
      "2 cups sushi rice, cooked and seasoned",
      "4 sheets nori",
      "1 avocado, sliced",
      "1 cucumber, julienned",
      "1/2 cup pickled radish, julienned",
      "2 tbsp rice vinegar",
      "Soy sauce and pickled ginger, to serve",
    ],
    instructions: [
      "Lay nori shiny-side down on a bamboo mat and spread a thin layer of sushi rice.",
      "Arrange avocado, cucumber, and pickled radish in a line across the rice.",
      "Roll tightly using the bamboo mat, sealing the edge with a dab of water.",
      "Slice each roll into 6-8 pieces with a sharp, wet knife.",
      "Serve with soy sauce and pickled ginger.",
    ],
    cuisineType: "Japanese",
    dietType: "vegan",
    prepTimeMinutes: 40,
    difficulty: "Medium",
    imageUrl: photo("1600891964092-4316c288032e"),
    ratingAverage: 4.3,
    ratingCount: 45,
  },
  {
    title: "Loaded Veggie Quesadillas",
    shortDescription: "Melty cheese quesadillas packed with peppers and beans.",
    fullDescription:
      "Flour tortillas stuffed with black beans, roasted peppers, corn, and melted cheese, griddled until crisp. A fast, satisfying vegetarian dinner.",
    ingredients: [
      "4 large flour tortillas",
      "1 can black beans, drained",
      "1 bell pepper, sliced and roasted",
      "1/2 cup corn kernels",
      "1.5 cups shredded cheese blend",
      "1 tsp cumin",
      "1 tsp chili powder",
      "Sour cream and salsa, to serve",
    ],
    instructions: [
      "Mash half the black beans with cumin and chili powder, leaving the rest whole.",
      "Spread beans, roasted peppers, corn, and cheese over half of each tortilla.",
      "Fold tortillas over and griddle on a dry skillet until golden and crisp on both sides.",
      "Cut into wedges and serve with sour cream and salsa.",
    ],
    cuisineType: "Mexican",
    dietType: "vegetarian",
    prepTimeMinutes: 20,
    difficulty: "Easy",
    imageUrl: photo("1600335895229-6e75511892c8"),
    ratingAverage: 4.2,
    ratingCount: 88,
  },
  {
    title: "Carne Asada Street Tacos",
    shortDescription: "Grilled marinated steak tacos with onion and cilantro.",
    fullDescription:
      "Skirt steak marinated in citrus, garlic, and chilies, grilled hot and fast, then chopped and piled onto warm corn tortillas with onion and cilantro.",
    ingredients: [
      "1.5 lbs skirt steak",
      "Juice of 2 limes",
      "Juice of 1 orange",
      "3 cloves garlic, minced",
      "1 tbsp chipotle in adobo, minced",
      "12 small corn tortillas",
      "1/2 white onion, diced",
      "Fresh cilantro, chopped",
      "Lime wedges, to serve",
    ],
    instructions: [
      "Marinate steak in lime juice, orange juice, garlic, and chipotle for at least 1 hour.",
      "Grill steak over high heat, 3-4 minutes per side for medium-rare.",
      "Rest steak, then chop into small pieces.",
      "Warm tortillas and fill with chopped steak.",
      "Top with diced onion, cilantro, and a squeeze of lime.",
    ],
    cuisineType: "Mexican",
    dietType: "non-veg",
    prepTimeMinutes: 30,
    difficulty: "Medium",
    imageUrl: photo("1568569350062-ebfa3cb195df"),
    ratingAverage: 4.8,
    ratingCount: 231,
  },
  {
    title: "Greek Village Salad",
    shortDescription: "Crisp cucumber, tomato, and feta salad with olive oil.",
    fullDescription:
      "A rustic Horiatiki salad of ripe tomatoes, cucumber, red onion, olives, and a thick slab of feta, dressed simply with olive oil and oregano. No lettuce needed.",
    ingredients: [
      "4 ripe tomatoes, cut into wedges",
      "1 cucumber, sliced",
      "1/2 red onion, thinly sliced",
      "1/2 cup kalamata olives",
      "200g block feta cheese",
      "1/4 cup olive oil",
      "1 tsp dried oregano",
      "Salt to taste",
    ],
    instructions: [
      "Combine tomatoes, cucumber, red onion, and olives in a large bowl.",
      "Place the block of feta whole on top of the salad.",
      "Drizzle generously with olive oil and sprinkle with oregano and salt.",
      "Serve family-style, breaking the feta apart at the table.",
    ],
    cuisineType: "Mediterranean",
    dietType: "vegetarian",
    prepTimeMinutes: 15,
    difficulty: "Easy",
    imageUrl: photo("1548943487-a2e4e43b4853"),
    ratingAverage: 4.6,
    ratingCount: 143,
  },
  {
    title: "Bengali Vegetable Khichuri",
    shortDescription: "Comforting rice and lentil stew with mixed vegetables.",
    fullDescription:
      "A one-pot Bengali staple of rice and moong dal simmered with cauliflower, potato, and peas, warmed with cumin, bay leaf, and ginger. Fully plant-based comfort food.",
    ingredients: [
      "1 cup rice",
      "1/2 cup moong dal, roasted",
      "1 potato, cubed",
      "1 cup cauliflower florets",
      "1/2 cup green peas",
      "1 tsp cumin seeds",
      "2 bay leaves",
      "1 tbsp ginger paste",
      "1 tsp turmeric",
      "3 tbsp mustard oil",
    ],
    instructions: [
      "Dry roast moong dal until fragrant, then rinse with rice.",
      "Heat mustard oil, temper with cumin seeds and bay leaves.",
      "Add ginger paste, potato, cauliflower, and turmeric, stir briefly.",
      "Add rice and dal along with 4 cups water, bring to a boil.",
      "Simmer until rice and dal are soft and porridge-like, stirring in peas near the end.",
      "Serve hot with a drizzle of ghee substitute or extra mustard oil.",
    ],
    cuisineType: "Bengali",
    dietType: "vegan",
    prepTimeMinutes: 40,
    difficulty: "Easy",
    imageUrl: photo("1603133872878-684f208fb84b"),
    ratingAverage: 4.3,
    ratingCount: 37,
  },
  {
    title: "Kung Pao Cauliflower",
    shortDescription: "Crispy cauliflower tossed in a spicy Sichuan pepper sauce.",
    fullDescription:
      "Battered cauliflower florets fried until crisp, then tossed in a classic sweet-spicy kung pao sauce with peanuts and dried chilies - a fully vegetarian take on the wok classic.",
    ingredients: [
      "1 head cauliflower, cut into florets",
      "1/2 cup cornstarch",
      "3 tbsp soy sauce",
      "2 tbsp rice vinegar",
      "1 tbsp hoisin sauce",
      "1 tbsp sugar",
      "6 dried red chilies",
      "1/2 cup roasted peanuts",
      "3 scallions, chopped",
      "2 cloves garlic, minced",
    ],
    instructions: [
      "Toss cauliflower florets in cornstarch and fry or air-fry until crisp.",
      "Whisk soy sauce, rice vinegar, hoisin, and sugar into a sauce.",
      "Stir-fry dried chilies and garlic in a hot wok until fragrant.",
      "Add the sauce and simmer until slightly thickened.",
      "Toss in fried cauliflower and peanuts, coating evenly.",
      "Garnish with scallions and serve over steamed rice.",
    ],
    cuisineType: "Chinese",
    dietType: "vegetarian",
    prepTimeMinutes: 35,
    difficulty: "Medium",
    imageUrl: photo("1516684732162-798a0062be99"),
    ratingAverage: 4.4,
    ratingCount: 68,
  },
  {
    title: "Kung Pao Chicken",
    shortDescription: "Diced chicken and peanuts in a spicy Sichuan stir-fry sauce.",
    fullDescription:
      "Tender diced chicken stir-fried with dried chilies, Sichuan peppercorns, and roasted peanuts in a glossy sweet-savory sauce. A takeout favorite made at home.",
    ingredients: [
      "1.5 lbs boneless chicken thighs, diced",
      "3 tbsp soy sauce",
      "2 tbsp rice vinegar",
      "1 tbsp hoisin sauce",
      "1 tsp Sichuan peppercorns",
      "6 dried red chilies",
      "1/2 cup roasted peanuts",
      "3 scallions, chopped",
      "2 cloves garlic, minced",
      "2 tbsp vegetable oil",
    ],
    instructions: [
      "Marinate diced chicken briefly in a splash of soy sauce and cornstarch.",
      "Stir-fry chicken in hot oil until browned and cooked through, set aside.",
      "In the same wok, toast Sichuan peppercorns and dried chilies until fragrant.",
      "Add garlic, then whisk in soy sauce, rice vinegar, and hoisin.",
      "Return chicken to the wok along with peanuts, tossing to coat.",
      "Garnish with scallions and serve over steamed rice.",
    ],
    cuisineType: "Chinese",
    dietType: "non-veg",
    prepTimeMinutes: 30,
    difficulty: "Medium",
    imageUrl: photo("1560684352-8497838a2229"),
    ratingAverage: 4.7,
    ratingCount: 198,
  },
  {
    title: "Thai Green Curry Vegetables",
    shortDescription: "Coconut green curry loaded with seasonal vegetables.",
    fullDescription:
      "A fragrant green curry made with green chilies, lemongrass, and coconut milk, simmered with eggplant, bell pepper, and green beans. Made vegetarian with soy sauce in place of fish sauce.",
    ingredients: [
      "3 tbsp green curry paste",
      "1 can coconut milk",
      "1 Thai eggplant, cubed",
      "1 bell pepper, sliced",
      "1 cup green beans, trimmed",
      "1 tbsp soy sauce",
      "1 tsp brown sugar",
      "Thai basil leaves",
      "1 red chili, sliced, for garnish",
    ],
    instructions: [
      "Simmer green curry paste in the thick part of the coconut milk until fragrant.",
      "Add remaining coconut milk, soy sauce, and brown sugar.",
      "Add eggplant, bell pepper, and green beans, simmer until tender.",
      "Stir in Thai basil leaves just before serving.",
      "Garnish with sliced chili and serve with jasmine rice.",
    ],
    cuisineType: "Thai",
    dietType: "vegetarian",
    prepTimeMinutes: 30,
    difficulty: "Easy",
    imageUrl: photo("1631515243349-e0cb75fb8d3a"),
    ratingAverage: 4.5,
    ratingCount: 79,
  },
  {
    title: "Paneer Butter Masala",
    shortDescription: "Soft paneer cubes in a creamy tomato-cashew curry.",
    fullDescription:
      "Pan-fried paneer simmered in a velvety tomato and cashew gravy, finished with butter and cream. A beloved North Indian restaurant classic, made vegetarian.",
    ingredients: [
      "400g paneer, cubed",
      "3 tomatoes, pureed",
      "1/4 cup cashews, soaked",
      "1 onion, chopped",
      "1 tbsp ginger-garlic paste",
      "1 tsp garam masala",
      "1 tsp kashmiri chili powder",
      "3 tbsp butter",
      "2 tbsp cream",
      "Fresh coriander, for garnish",
    ],
    instructions: [
      "Lightly pan-fry paneer cubes until golden, set aside.",
      "Sauté onion and ginger-garlic paste in butter until soft.",
      "Blend with tomato puree and soaked cashews into a smooth gravy.",
      "Return the gravy to the pan, add garam masala and chili powder, simmer.",
      "Add paneer cubes and cream, simmer 5 minutes.",
      "Garnish with coriander and serve with naan or rice.",
    ],
    cuisineType: "Indian",
    dietType: "vegetarian",
    prepTimeMinutes: 35,
    difficulty: "Medium",
    imageUrl: photo("1512003867696-6d5ce6835040"),
    ratingAverage: 4.8,
    ratingCount: 267,
  },
  {
    title: "Chicken Tikka Masala",
    shortDescription: "Grilled marinated chicken in a creamy spiced tomato sauce.",
    fullDescription:
      "Yogurt-marinated chicken chunks charred until smoky, then simmered in a rich tomato and cream sauce spiced with garam masala. A curry-house favorite.",
    ingredients: [
      "1.5 lbs chicken thighs, cubed",
      "1/2 cup yogurt",
      "1 tbsp ginger-garlic paste",
      "2 tsp garam masala",
      "1 tsp paprika",
      "3 tomatoes, pureed",
      "1 onion, chopped",
      "1/2 cup cream",
      "2 tbsp butter",
      "Fresh coriander, for garnish",
    ],
    instructions: [
      "Marinate chicken in yogurt, ginger-garlic paste, and half the spices for at least 30 minutes.",
      "Grill or broil chicken until charred at the edges.",
      "Sauté onion in butter, add remaining spices and tomato puree, simmer.",
      "Blend the sauce smooth, then return to the pan and stir in cream.",
      "Add grilled chicken and simmer 10 minutes.",
      "Garnish with coriander and serve with rice or naan.",
    ],
    cuisineType: "Indian",
    dietType: "non-veg",
    prepTimeMinutes: 45,
    difficulty: "Medium",
    imageUrl: photo("1618889482923-38250401a84e"),
    ratingAverage: 4.9,
    ratingCount: 284,
  },
  {
    title: "Chana Masala",
    shortDescription: "Spiced chickpea curry simmered in tangy tomato gravy.",
    fullDescription:
      "Chickpeas simmered with onion, tomato, and a warm blend of cumin, coriander, and amchur (dried mango powder) for a tangy kick. Naturally vegan and packed with protein.",
    ingredients: [
      "2 cans chickpeas, drained",
      "2 tomatoes, pureed",
      "1 onion, chopped",
      "1 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "2 tsp coriander powder",
      "1 tsp amchur (dried mango powder)",
      "1/2 tsp garam masala",
      "3 tbsp oil",
      "Fresh coriander, for garnish",
    ],
    instructions: [
      "Heat oil and temper with cumin seeds.",
      "Add onion and ginger-garlic paste, sauté until golden.",
      "Stir in tomato puree, coriander powder, and amchur, cook until oil separates.",
      "Add chickpeas and a splash of water, simmer 15 minutes.",
      "Mash a few chickpeas to thicken the gravy naturally.",
      "Finish with garam masala and garnish with coriander.",
    ],
    cuisineType: "Indian",
    dietType: "vegan",
    prepTimeMinutes: 30,
    difficulty: "Easy",
    imageUrl: photo("1625944230945-1b7dd3b949ab"),
    ratingAverage: 4.5,
    ratingCount: 121,
  },
  {
    title: "French Onion Soup",
    shortDescription: "Caramelized onion soup topped with toasted cheese crouton.",
    fullDescription:
      "Onions slow-caramelized for over an hour in butter, simmered in a savory vegetable stock, and finished under the broiler with a Gruyere-topped baguette crouton.",
    ingredients: [
      "4 large onions, thinly sliced",
      "4 tbsp butter",
      "6 cups vegetable stock",
      "1/2 cup dry white wine",
      "1 bay leaf",
      "1 baguette, sliced",
      "1.5 cups Gruyere cheese, grated",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Melt butter in a heavy pot and cook onions on low heat for 45-60 minutes, stirring often, until deeply caramelized.",
      "Deglaze with white wine, then add stock and bay leaf, simmer 20 minutes.",
      "Season with salt and pepper, discard bay leaf.",
      "Ladle soup into oven-safe bowls, top with toasted baguette slices and grated Gruyere.",
      "Broil until the cheese is bubbling and golden, then serve immediately.",
    ],
    cuisineType: "French",
    dietType: "vegetarian",
    prepTimeMinutes: 90,
    difficulty: "Medium",
    imageUrl: photo("1600628421055-4d30de868b8f"),
    ratingAverage: 4.6,
    ratingCount: 103,
  },
  {
    title: "Coq au Vin",
    shortDescription: "Chicken braised in red wine with mushrooms and bacon.",
    fullDescription:
      "A rustic French classic - chicken thighs braised low and slow in red wine with pearl onions, mushrooms, and smoky bacon until deeply flavorful and tender.",
    ingredients: [
      "6 chicken thighs, bone-in",
      "6 strips bacon, chopped",
      "1 cup pearl onions",
      "2 cups mushrooms, quartered",
      "2 cups dry red wine",
      "1 cup chicken stock",
      "2 cloves garlic, minced",
      "1 bay leaf",
      "2 tbsp flour",
      "Fresh thyme, for garnish",
    ],
    instructions: [
      "Render bacon in a heavy pot until crisp, remove and set aside.",
      "Brown chicken thighs in the bacon fat, then remove.",
      "Sauté pearl onions, mushrooms, and garlic in the same pot.",
      "Stir in flour, then deglaze with red wine and add stock and bay leaf.",
      "Return chicken and bacon to the pot, cover, and braise 45 minutes until tender.",
      "Garnish with fresh thyme and serve with crusty bread or mashed potatoes.",
    ],
    cuisineType: "French",
    dietType: "non-veg",
    prepTimeMinutes: 75,
    difficulty: "Hard",
    imageUrl: photo("1533089860892-a7c6f0a88666"),
    ratingAverage: 4.7,
    ratingCount: 86,
  },
  {
    title: "Loaded Veggie Burger",
    shortDescription: "Black bean patty stacked with all the classic fixings.",
    fullDescription:
      "A hearty black bean and oat patty, pan-seared until crisp, stacked on a toasted bun with lettuce, tomato, and a smoky mayo. A diner classic, made vegetarian.",
    ingredients: [
      "2 cans black beans, drained and mashed",
      "1/2 cup rolled oats",
      "1 egg",
      "1 tsp smoked paprika",
      "1 tsp cumin",
      "4 burger buns",
      "Lettuce, tomato, and red onion, sliced",
      "3 tbsp mayonnaise",
      "1 tsp chipotle hot sauce",
    ],
    instructions: [
      "Mix mashed black beans, oats, egg, paprika, and cumin into a firm patty mixture.",
      "Form into 4 patties and chill for 15 minutes.",
      "Pan-sear patties until crisp and heated through, about 4 minutes per side.",
      "Mix mayonnaise with chipotle hot sauce for a smoky spread.",
      "Assemble burgers with lettuce, tomato, onion, and the smoky mayo.",
    ],
    cuisineType: "American",
    dietType: "vegetarian",
    prepTimeMinutes: 30,
    difficulty: "Easy",
    imageUrl: photo("1584949091598-c31daaaa4aa9"),
    ratingAverage: 4.3,
    ratingCount: 95,
  },
  {
    title: "BBQ Pulled Pork Sliders",
    shortDescription: "Slow-cooked pulled pork piled onto soft slider buns.",
    fullDescription:
      "Pork shoulder rubbed with spices and slow-cooked until it shreds effortlessly, tossed in a tangy barbecue sauce, and piled onto soft slider buns with coleslaw.",
    ingredients: [
      "3 lbs pork shoulder",
      "2 tbsp brown sugar",
      "1 tbsp smoked paprika",
      "1 tsp garlic powder",
      "1.5 cups barbecue sauce",
      "12 slider buns",
      "2 cups coleslaw mix",
      "2 tbsp mayonnaise",
      "1 tbsp apple cider vinegar",
    ],
    instructions: [
      "Rub pork shoulder with brown sugar, smoked paprika, and garlic powder.",
      "Slow-cook on low for 7-8 hours until it shreds easily with a fork.",
      "Shred the pork and toss with barbecue sauce.",
      "Toss coleslaw mix with mayonnaise and apple cider vinegar.",
      "Pile pulled pork onto slider buns and top with coleslaw.",
    ],
    cuisineType: "American",
    dietType: "non-veg",
    prepTimeMinutes: 480,
    difficulty: "Medium",
    imageUrl: photo("1518492104633-130d0cc84637"),
    ratingAverage: 4.8,
    ratingCount: 176,
  },
  {
    title: "Vegan Mac and Cheese",
    shortDescription: "Creamy dairy-free mac and cheese made with cashews.",
    fullDescription:
      "Elbow macaroni coated in a rich, cheesy sauce made from soaked cashews, nutritional yeast, and roasted butternut squash - no dairy, all comfort.",
    ingredients: [
      "12 oz elbow macaroni",
      "1 cup cashews, soaked",
      "1 cup roasted butternut squash",
      "1/2 cup nutritional yeast",
      "1 tbsp lemon juice",
      "1 tsp garlic powder",
      "1 tsp smoked paprika",
      "1 cup unsweetened plant milk",
      "Salt to taste",
    ],
    instructions: [
      "Cook macaroni in salted water until al dente, drain.",
      "Blend cashews, roasted squash, nutritional yeast, lemon juice, garlic powder, and plant milk until smooth.",
      "Warm the sauce in a saucepan, season with smoked paprika and salt.",
      "Toss the cooked macaroni with the sauce until fully coated.",
      "Serve warm, optionally topped with breadcrumbs or extra paprika.",
    ],
    cuisineType: "American",
    dietType: "vegan",
    prepTimeMinutes: 30,
    difficulty: "Easy",
    imageUrl: photo("1512152272829-e3139592d56f"),
    ratingAverage: 4.2,
    ratingCount: 54,
  },
  {
    title: "Vegetable Bibimbap",
    shortDescription: "Rice bowl topped with seasoned vegetables and gochujang.",
    fullDescription:
      "A colorful Korean rice bowl topped with individually seasoned spinach, carrots, mushrooms, and bean sprouts, finished with a fried egg and spicy gochujang sauce.",
    ingredients: [
      "2 cups cooked short-grain rice",
      "1 cup spinach, blanched",
      "1 carrot, julienned and sautéed",
      "1 cup mushrooms, sautéed",
      "1 cup bean sprouts, blanched",
      "2 eggs, fried",
      "2 tbsp gochujang",
      "1 tbsp sesame oil",
      "Sesame seeds, for garnish",
    ],
    instructions: [
      "Season each vegetable lightly with sesame oil and salt after cooking.",
      "Divide rice into bowls and arrange vegetables in sections on top.",
      "Top each bowl with a fried egg.",
      "Add a spoonful of gochujang to each bowl.",
      "Sprinkle with sesame seeds and mix everything together before eating.",
    ],
    cuisineType: "Korean",
    dietType: "vegetarian",
    prepTimeMinutes: 35,
    difficulty: "Medium",
    imageUrl: photo("1553163147-622ab57be1c7"),
    ratingAverage: 4.5,
    ratingCount: 112,
  },
  {
    title: "Korean Fried Chicken",
    shortDescription: "Double-fried chicken glazed in a sweet-spicy sauce.",
    fullDescription:
      "Chicken wings double-fried for a shatteringly crisp crust, then tossed in a sticky gochujang and honey glaze. Korean fried chicken done right.",
    ingredients: [
      "2 lbs chicken wings",
      "1 cup cornstarch",
      "Oil, for frying",
      "3 tbsp gochujang",
      "2 tbsp honey",
      "2 tbsp soy sauce",
      "2 cloves garlic, minced",
      "1 tbsp rice vinegar",
      "Sesame seeds and scallions, for garnish",
    ],
    instructions: [
      "Coat chicken wings in cornstarch and fry at 325°F until light golden, then remove.",
      "Raise oil temperature to 375°F and fry wings a second time until deeply crisp.",
      "Whisk gochujang, honey, soy sauce, garlic, and rice vinegar into a glaze, warming briefly.",
      "Toss fried wings in the glaze until fully coated.",
      "Garnish with sesame seeds and scallions before serving.",
    ],
    cuisineType: "Korean",
    dietType: "non-veg",
    prepTimeMinutes: 45,
    difficulty: "Medium",
    imageUrl: photo("1571091655789-405eb7a3a3a8"),
    ratingAverage: 4.8,
    ratingCount: 219,
  },
  {
    title: "Tofu Banh Mi",
    shortDescription: "Crispy marinated tofu on a baguette with pickled veg.",
    fullDescription:
      "A Vietnamese sandwich stacked with crispy pan-fried marinated tofu, quick-pickled carrot and daikon, cucumber, and fresh herbs on a crusty baguette.",
    ingredients: [
      "1 block firm tofu, sliced",
      "3 tbsp soy sauce",
      "1 tbsp maple syrup",
      "1 carrot, julienned",
      "1/2 daikon radish, julienned",
      "3 tbsp rice vinegar",
      "1 baguette",
      "1/2 cucumber, sliced",
      "Fresh cilantro and jalapeño, sliced",
      "Vegan mayo, for spreading",
    ],
    instructions: [
      "Marinate tofu slices in soy sauce and maple syrup for 15 minutes.",
      "Quick-pickle carrot and daikon in rice vinegar with a pinch of salt and sugar.",
      "Pan-fry marinated tofu until crisp on both sides.",
      "Slice baguette and spread with vegan mayo.",
      "Layer tofu, pickled vegetables, cucumber, cilantro, and jalapeño into the baguette.",
    ],
    cuisineType: "Vietnamese",
    dietType: "vegetarian",
    prepTimeMinutes: 30,
    difficulty: "Easy",
    imageUrl: photo("1559847844-5315695dadae"),
    ratingAverage: 4.4,
    ratingCount: 58,
  },
  {
    title: "Beef Pho",
    shortDescription: "Aromatic beef noodle soup with star anise broth.",
    fullDescription:
      "A deeply aromatic Vietnamese noodle soup - beef bones and brisket simmered for hours with star anise, cinnamon, and charred ginger, served over rice noodles with fresh herbs.",
    ingredients: [
      "2 lbs beef bones",
      "1 lb beef brisket",
      "1 onion, charred",
      "1 knob ginger, charred",
      "3 star anise",
      "1 cinnamon stick",
      "1 tbsp fish sauce",
      "8 oz rice noodles",
      "Bean sprouts, Thai basil, and lime, to serve",
      "Thinly sliced raw beef, for topping",
    ],
    instructions: [
      "Simmer beef bones and brisket with charred onion and ginger for at least 3 hours, skimming often.",
      "Add star anise and cinnamon stick during the last hour of simmering.",
      "Strain the broth and season with fish sauce.",
      "Cook rice noodles according to package instructions.",
      "Divide noodles into bowls, top with sliced brisket and raw beef, and ladle over hot broth.",
      "Serve with bean sprouts, Thai basil, and lime on the side.",
    ],
    cuisineType: "Vietnamese",
    dietType: "non-veg",
    prepTimeMinutes: 240,
    difficulty: "Hard",
    imageUrl: photo("1607013251379-e6eecfffe234"),
    ratingAverage: 4.9,
    ratingCount: 256,
  },
  {
    title: "Vegetable Pho Chay",
    shortDescription: "Fragrant vegetable broth noodle soup, fully plant-based.",
    fullDescription:
      "A vegan take on pho, with a broth simmered from charred onion, ginger, and warming spices, served over rice noodles with tofu, mushrooms, and fresh herbs.",
    ingredients: [
      "1 onion, charred",
      "1 knob ginger, charred",
      "3 star anise",
      "1 cinnamon stick",
      "6 cups vegetable stock",
      "1 tbsp soy sauce",
      "1 block firm tofu, pan-fried and sliced",
      "1 cup mushrooms, sliced",
      "8 oz rice noodles",
      "Bean sprouts, Thai basil, and lime, to serve",
    ],
    instructions: [
      "Simmer vegetable stock with charred onion, ginger, star anise, and cinnamon for 30 minutes.",
      "Strain the broth and season with soy sauce.",
      "Cook rice noodles according to package instructions.",
      "Divide noodles into bowls and top with pan-fried tofu and mushrooms.",
      "Ladle hot broth over the top and serve with bean sprouts, Thai basil, and lime.",
    ],
    cuisineType: "Vietnamese",
    dietType: "vegan",
    prepTimeMinutes: 45,
    difficulty: "Medium",
    imageUrl: photo("1544785349-c4a5301826fd"),
    ratingAverage: 4.5,
    ratingCount: 67,
  },
];

async function main() {
  await mongoose.connect(process.env.MONGODB_URI as string);

  const db = mongoose.connection.db;
  if (!db) {
    throw new Error("Mongoose connection has no database handle");
  }

  const demoUser = await db.collection("user").findOne({ email: "demo@mealmind.ai" });
  if (!demoUser) {
    throw new Error(
      "Demo user not found - run `npx ts-node scripts/seedDemoUser.ts` first."
    );
  }
  const createdBy = demoUser._id;

  // Fix pre-existing recipes mislabeled dietType: "none" (should be
  // "non-veg") - otherwise their cuisine's non-veg filter combo
  // incorrectly returns zero results despite a matching dish existing.
  const fixResult = await Recipe.updateMany({ dietType: "none" }, { $set: { dietType: "non-veg" } });
  console.log(`Fixed ${fixResult.modifiedCount} pre-existing recipes mislabeled dietType: "none" -> "non-veg"`);

  const docs = RECIPES.map((r) => ({ ...r, createdBy }));
  const inserted = await Recipe.insertMany(docs);

  const total = await Recipe.countDocuments();
  console.log(`Inserted ${inserted.length} recipes.`);
  console.log(`Total recipes in database: ${total}`);

  await mongoose.disconnect();
}

main().catch((err) => {
  console.error("Seeding failed:", err);
  process.exit(1);
});
